### ### KINEMATIC QUANTITIES:
#Leg order for kinematics is: [FR,RR,FL,BL]
#Angle order for kinematics is [Housing, InnerHip, InnerShank, OuterHip, OuterShank] -> see motor_ids
name: 
  - FrontRight_motorHousing_hipAduction_motor6
  - FrontRight_hip_inner_motor5
  - FrontRight_shank_inner_knee
  - FrontRight_hip_outer_motor4
  - FrontRight_shank_outer_knee
  - BackRight_motorHousing_hipAduction_motor12
  - BackRight_hip_inner_motor11
  - BackRight_shank_inner_knee
  - BackRight_hip_outer_motor10
  - BackRight_shank_outer_knee
  - FrontLeft_motorHousing_hipAduction_motor3
  - FrontLeft_hip_inner_motor2
  - FrontLeft_shank_inner_knee
  - FrontLeft_hip_outer_motor1
  - FrontLeft_shank_outer_knee
  - BackLeft_motorHousing_hipAduction_motor9
  - BackLeft_hip_inner_motor8
  - BackLeft_shank_inner_knee
  - BackLeft_hip_outer_motor7
  - BackLeft_shank_outer_knee
motor_ids:        [5,4,3,11,10, 9,2,1,0,8,7,6]     #for kinematics

### ### ROBOT QUANTITIES:
#for robot (Last minute quick fix if something changes) 
#Leg order for robot is: [FL,FR,BL,BR]
#Angle order for robot is [Outer, Inner, Housing]
robot_signs:      [1,1,1, 1,1,1, 1,1,1, 1,1,1]  # They should be all ones normally)   
