robot_name: "olympus"

#============= GENERAL

base_joint_type: 1 #choose from [0: weld, 1: revolute_x, 2: revolute_y, 3: revolute_z, 4: floating]

testbed_params:
  # Horizontal Distance of the attachement point for each configuration:
  roll_DX: -0.076   #measured from cad
  pitch_DX: 0.076  #measured from cad
  yaw_DX: 0.0
  # Damping for each configuration:
  damping_roll: 1e-3
  damping_pitch: 1e-3
  damping_yaw: 1e-3

# Dynamic Parameters:
motor_limits: [ 4,4,4]    # [Mh,HI,HO]

controller_gains:
  Kp: [ 20,  5.7296,  5.7296] # [Mh,HI,HO]
  Kd: [2.2,  0.0573,  0.0573] # [Mh,HI,HO]
  Ki: [ 45,  0.0057,  0.0057]

add_leg_spring: false
spring_params:
  stiffness: 0
  damping: 0
  free_length: 0.175

bushing_params:
  torque_stiffness: [      0,      0,  0]
  torque_damping:   [      0,      0,  0]
  force_stiffness:  [    3e4,    3e4,  0]
  force_damping:    [  2.5e2,  2.5e2,  0]


#============= URDF SPECIFIC
#change if URDF is updated

#Import from URDF. (Update from Olympus v2, 30/6/24)
# Requirements:
#1. Legs must be in the same order in joints and bodies (eg. FR,BR,FL,BL)
#2. Order of leg links/joints must be  [Mh, HI, SI, HO, SO], as (controllers, bushing etc are hardcoded)
# Mh: MotorHousing, HI: Hip Inner, SI: Shank Inner, HO: Hip Outer, SO: Shank Outer

joint_names: #Order according to this: [Mh, HI, SI, HO, SO]
  FrontRight:
    - FrontRight_motorHousing_hipAduction_motor6
    - FrontRight_hip_inner_motor5
    - FrontRight_shank_inner_knee
    - FrontRight_hip_outer_motor4
    - FrontRight_shank_outer_knee
  BackRight:
    - BackRight_motorHousing_hipAduction_motor12
    - BackRight_hip_inner_motor11
    - BackRight_shank_inner_knee
    - BackRight_hip_outer_motor10
    - BackRight_shank_outer_knee
  FrontLeft:
    - FrontLeft_motorHousing_hipAduction_motor3
    - FrontLeft_hip_inner_motor2
    - FrontLeft_shank_inner_knee
    - FrontLeft_hip_outer_motor1
    - FrontLeft_shank_outer_knee
  BackLeft:
    - BackLeft_motorHousing_hipAduction_motor9
    - BackLeft_hip_inner_motor8
    - BackLeft_shank_inner_knee
    - BackLeft_hip_outer_motor7
    - BackLeft_shank_outer_knee
body_names:  #Order according to this: [Mh, HI, SI, HO, SO]
  FrontRight:
    - FrontRight_motorHousing
    - FrontRight_hip_inner
    - FrontRight_shank_inner
    - FrontRight_hip_outer
    - FrontRight_shank_outer
    - FrontRight_paw
  BackRight:
    - BackRight_motorHousing
    - BackRight_hip_inner
    - BackRight_shank_inner
    - BackRight_hip_outer
    - BackRight_shank_outer
    - BackRight_paw
  FrontLeft:
    - FrontLeft_motorHousing
    - FrontLeft_hip_inner
    - FrontLeft_shank_inner
    - FrontLeft_hip_outer
    - FrontLeft_shank_outer
    - FrontLeft_paw
  BackLeft:
    - BackLeft_motorHousing
    - BackLeft_hip_inner
    - BackLeft_shank_inner
    - BackLeft_hip_outer
    - BackLeft_shank_outer
    - BackLeft_paw
torso_name: "Body"